---
- name: be sure httpd is installed
  yum: name=httpd state=installed
- name: Configure Apache<-(ajp)->Tomcat
  template: src=proxy_ajp.conf dest=/etc/httpd/conf.d/
- name: be sure httpd is running and enabled
  service: name=httpd state=running enabled=yes
